# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('conclusion', models.TextField()),
                ('summary', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('agenda', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Agenda')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='agendaaction',
            name='agenda_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.AgendaDetail'),
        ),
    ]
