# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('projects', '0002_auto_20161011_2039'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParticipators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='agenda',
        ),
        migrations.AddField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authorization.UserProfile'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='agendadetail',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendadetail',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendadetail',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendadetail',
            name='topic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meetingroles',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingType'),
        ),
        migrations.AddField(
            model_name='meetingparticipators',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='meetingparticipators',
            name='participator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.TeamMembers'),
        ),
        migrations.AddField(
            model_name='meetingparticipators',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingRoles'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilitator_user_profile', to='meetings.MeetingParticipators'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='time_keeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_keeper_user_profile', to='meetings.MeetingParticipators'),
        ),
        migrations.AddField(
            model_name='agendaaction',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingParticipators'),
        ),
        migrations.AddField(
            model_name='agendadetail',
            name='presenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingParticipators'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingType'),
        ),
    ]
